function serial = hfss_xfm_cross(fid,X , Y, Z, W, S, OP, Thickness, serial)
    hfssUDP(fid, 'xfm_cross', ['C' num2str(serial)], 8, {'Xpos', 'Ypos',  'Zpos','W','S', 'OPEN', 'Thickness', 'maskGrid'},...
            {[num2str(X) 'um'], [num2str(Y) 'um'], [num2str(Z) 'um'],...
            [num2str(W) 'um'], [num2str(S) 'um'], [num2str(OP) 'um'], ...
            [num2str(Thickness) 'um'], '0.005'}, '" & Chr(34) & "copper" & Chr(34) & "');
    serial = serial + 1;