function serial = hfss_xfm_cross_via(fid,X , Y, Z, W, S, OP, Thickness, viah, serial)
    hfssUDP(fid, 'xfm_cross_via', ['C' num2str(serial)], 9, {'Xpos', 'Ypos',  'Zpos','W','S', 'OPEN', 'Thickness', 'maskGrid','viah'},...
            {[num2str(X) 'um'], [num2str(Y) 'um'], [num2str(Z) 'um'],...
            [num2str(W) 'um'], [num2str(S) 'um'], [num2str(OP) 'um'], ...
            [num2str(Thickness) 'um'], '0.005', [num2str(viah) 'um']}, '" & Chr(34) & "copper" & Chr(34) & "');
    serial = serial + 1;