function hfss_IND(fid,X , Y, Z, W, S, OD, NT, Thickness)
        hfssUDP(fid, 'inductor', 'L0', 11, {'Xpos', 'Ypos',  'Zpos','W','S', 'OD','NT', 'Thickness', 'maskGrid', 'DIV', 'lead'},...
            {[num2str(X) 'um'], [num2str(Y) 'um'], [num2str(Z) 'um'],...
            [num2str(W) 'um'], [num2str(S) 'um'], [num2str(OD) 'um'],...
            num2str(NT), Thickness, '0.005um', '3.2', '2um'});