function serial = hfss_xfm_halfud(fid,X , Y, Z, W, R_OP,L_OP, OD,Thickness, serial)
    hfssUDP(fid, 'xfm_half', ['L' num2str(serial)], 10, {'Xpos', 'Ypos',  'Zpos','OD','W','L_OP', 'R_OP', 'Thickness', 'maskGrid', 'DIV'},...
            {[num2str(X) 'um'], [num2str(Y) 'um'], [num2str(Z) 'um'],[num2str(OD) 'um'],...
            [num2str(W) 'um'], [num2str(L_OP) 'um'], [num2str(R_OP) 'um'], ...
            [num2str(Thickness) 'um'], '0.005', '3.2'}, '" & Chr(34) & "copper" & Chr(34) & "');
    hfssDuplicateMirror(fid, {['L' num2str(serial)]}, [0 0 0], [0 -1 0], '', false)
    serial = serial + 1;